export type DataType =
  | 'STRING'
  | 'TEXT'
  | 'INTEGER'
  | 'DECIMAL'
  | 'BOOLEAN'
  | 'DATE'
  | 'DATETIME'
  | 'DICTIONARY'
  | 'TABLE'
  | 'ENUMS'
  | 'ACCOUNT_PLAN'
  | 'CHARACTERISTICS_PLAN'
  | 'DOCUMENT'
  | 'EXCHANGE_PLAN'
  | 'CALCULATION_PLAN'
  | 'ACCUMULATION_REGISTER'
  | 'INFORMATION_REGISTER'
  | 'OBJECT'

export const IGNORED_DATA_TYPES = new Set<DataType>(['TABLE', 'OBJECT'])

export const DICT_DATA_TYPES = new Set<DataType>([
  'DICTIONARY',
  'ACCOUNT_PLAN',
  'CHARACTERISTICS_PLAN',
  'DOCUMENT',
  'EXCHANGE_PLAN',
  'CALCULATION_PLAN',
  'ACCUMULATION_REGISTER',
  'INFORMATION_REGISTER',
])
